/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  safelist: [
    'bg-primary-container',
    'bg-primary-fixed',
    'bg-secondary-fixed',
    'bg-tertiary-fixed',
    'text-on-primary-fixed-variant',
    'text-on-secondary-fixed-variant',
    'text-on-tertiary-fixed-variant',
    'border-secondary-fixed',
    'bg-primary-fixed-dim',
    'text-primary-fixed-dim',
    'bg-secondary-container',
    'text-on-secondary-container',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      colors: {
        primary: '#00375e',
        'primary-container': '#1f4e79',
        'on-primary': '#ffffff',
        'on-primary-container': '#95bff1',
        secondary: '#006c4e',
        'secondary-dark': '#005240',
        'secondary-container': '#83f5c6',
        'on-secondary-container': '#007151',
        'primary-fixed': '#d1e4ff',
        'primary-fixed-dim': '#a0cafc',
        'on-primary-fixed': '#001d35',
        'on-primary-fixed-variant': '#184974',
        'secondary-fixed': '#86f8c9',
        'secondary-fixed-dim': '#68dbae',
        'on-secondary-fixed': '#002115',
        'on-secondary-fixed-variant': '#00513a',
        'tertiary-fixed': '#ffddb5',
        'tertiary-fixed-dim': '#f5bc72',
        'on-tertiary-fixed-variant': '#643f00',
        'on-surface': '#191c1e',
        'on-surface-variant': '#42474f',
        'on-background': '#191c1e',
        outline: '#72777f',
        'outline-variant': '#c2c7d0',
        surface: '#f8f9fb',
        'surface-dim': '#d9dadc',
        'surface-bright': '#f8f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f6',
        'surface-container': '#edeef0',
        'surface-container-high': '#e7e8ea',
        'surface-container-highest': '#e1e2e4',
        'surface-variant': '#e1e2e4',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f3',
      },
    },
  },
  plugins: [],
};
